# Generated by Django 4.1.7 on 2023-03-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='dete',
            new_name='date',
        ),
    ]
